openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API para autenticação, registro e gestão de sessão

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        201:
          description: User registered and authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSessionResponse'
        400:
          description: Invalid input or email already in use

  /auth/login:
    post:
      summary: Authenticate user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSessionResponse'
        401:
          description: Invalid credentials

  /auth/refresh:
    post:
      summary: Refresh access token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        200:
          description: Tokens refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSessionResponse'
        400:
          description: Refresh token missing
        401:
          description: Invalid or expired refresh token

  /auth/me:
    get:
      summary: Get current authenticated user profile
      tags:
        - Auth
      security:
        - BearerAuth: []
      responses:
        200:
          description: Current user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        401:
          description: Unauthorized (Invalid or missing token)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    RegisterRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john@example.com"
        password:
          type: string
          format: password
          example: "StrongP@ssw0rd!"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "john@example.com"
        password:
          type: string
          format: password
          example: "StrongP@ssw0rd!"

    RefreshTokenRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          description: The refresh token received during login


    UserProfileResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string

    AuthSessionResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        accessToken:
          type: string
          description: JWT Access Token (short lived)
        refreshToken:
          type: string
          description: JWT Refresh Token (long lived)