openapi: 3.0.0
info:
  title: Classification API
  version: 1.0.0
  description: API para classificação de espécies utilizando IA e gestão de histórico

paths:
  /classifications/upload:
    post:
      summary: Enviar imagem para classificação
      description: Recebe uma imagem, processa via microserviço de IA e salva o resultado.
      tags:
        - Classification
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - userId
                - image
              properties:
                userId:
                  type: string
                  format: uuid
                  example: "550e8400-e29b-41d4-a716-446655440000"
                image:
                  type: string
                  format: binary
                  description: O arquivo de imagem (jpg, png, etc)
      responses:
        201:
          description: Imagem classificada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassificationResponse'
        400:
          description: Erro de validação ou campo 'image' ausente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /classifications/{id}:
    get:
      summary: Obter detalhes de uma classificação
      tags:
        - Classification
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Dados da classificação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassificationResponse'
        404:
          description: Classificação não encontrada

components:
  schemas:
    ClassificationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        nameSpecies:
          type: string
          example: "Rosa Rugosa"
        confidence:
          type: string
          example: "98.50%"
        classifiedAt:
          type: string
          format: date-time
        modelId:
          type: string
          example: "vgg16-plant-v1"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Image is required"