openapi: 3.0.0
info:
  title: User & Classification API
  version: 1.0.0
  description: API para gerenciamento de usuários e consulta de histórico de classificações.

paths:
  /user:
    post:
      summary: Criar um novo usuário
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        400:
          description: Entrada inválida ou e-mail já em uso

  /user/{id}:
    get:
      summary: Buscar usuário por ID
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        404:
          description: Usuário não encontrado

  /user/{id}/name:
    patch:
      summary: Alterar nome do usuário
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeUserNameRequest'
      responses:
        204:
          description: Nome atualizado com sucesso
        400:
          description: Dados inválidos
        404:
          description: Usuário não encontrado

  /user/classification/me:
    get:
      summary: Obter histórico do usuário autenticado
      description: Retorna todas as classificações pertencentes ao usuário logado via Token.
      tags:
        - User
      security:
        - BearerAuth: []
      responses:
        200:
          description: Lista de classificações do usuário
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClassificationResponse'
        401:
          description: Não autorizado

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserResponse:
      type: object
      properties:
        id: 
          type: string
          format: uuid
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john@example.com"

    CreateUserRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    ChangeUserNameRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "John New Name"

    ClassificationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nameSpecies:
          type: string
          example: "Rosa Rugosa"
        confidence:
          type: string
          example: "98.50%"
        classifiedAt:
          type: string
          format: date-time
        modelId:
          type: string
          example: "vgg16-plant-v1"